version: '3.8'  # Use the appropriate version of the Docker stack for your setup

services:
  web:
    image: nginx:latest  # Use the latest Nginx image from Docker Hub
    ports:
      - "82:82"  # Map port 82 on the host to port 82 on the containers
    deploy:
      replicas: 3  # Number of replicas you want to run in the swarm
      update_config:
        parallelism: 2  # Number of containers to update at a time during a rolling update
        delay: 10s  # Delay between updates during a rolling update
      restart_policy:
        condition: any  # Condition for container restarts (any, none, on-failure, etc.)
